[package]
name = "leptos_styles"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
grass = "0.13"
leptos = { version = "0.6.12", optional = true }

[features]
leptos = ["dep:leptos"]
